// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      label: 'About',
      id: 'README',
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/reference',
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/examples',
        },
      ],
    },
  ],
};

module.exports = sidebars;
